database_id : 7, 
file_id : 1, 
file_guid : null, 
type : 0, 
type_desc : ROWS, 
data_space_id : 1, 
name : IDMS_Data, 
physical_name : C:\IDMS\IDMS.mdf, 
state : 0, 
state_desc : ONLINE, 
size : 2448464, 
max_size : -1, 
growth : 10, 
is_media_read_only : 0, 
is_read_only : 0, 
is_sparse : 0, 
is_percent_growth : 1, 
is_name_reserved : 0,
create_lsn : null,
drop_lsn : null, 
read_only_lsn : null, 
read_write_lsn : null, 
differential_base_lsn : 606211000000009300168, 
differential_base_guid : B873FC26-2399-48E1-BFC4-6ACDC8A3AE96, 
differential_base_time : 2019-09-18 14:38:31.907, 
redo_start_lsn : null, 
redo_start_fork_guid : null, 
redo_target_lsn : null, 
redo_target_fork_guid : null, 
backup_lsn : 30170000000035900003,

database_id : 7, file_id : 2, file_guid : null, type : 1, type_desc : LOG, data_space_id : 0, name : IDMS_Log, physical_name : C:\IDMS\IDMS_log.ldf, state : 0, state_desc : ONLINE, size : 128, max_size : -1, growth : 10, is_media_read_only : 0, is_read_only : 0, is_sparse : 0, is_percent_growth : 1, is_name_reserved : 0, create_lsn : null, drop_lsn : null, read_only_lsn : null, read_write_lsn : null, differential_base_lsn : null, differential_base_guid : null, differential_base_time : null, redo_start_lsn : null, redo_start_fork_guid : null, redo_target_lsn : null, redo_target_fork_guid : null, backup_lsn : null, 
